image: WMF 5
environment:
  APIKey:
    secure: v711B0A/aGDr4wVCW3sYtaJJljC+rXipS2PENvcBC+qtOs4VXS9QWDTMJyQIKLTv

install:
  - choco install gitversion.portable -pre -y
  - rm C:\Tools\GitVersion\GitVersion.exe
  - ps: Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force

before_build:
  - ps: gitversion /l console /output buildserver
  - ps: Update-ModuleManifest -Path .\PSF.psd1 -ModuleVersion $env:GitVersion_MajorMinorPatch

build_script:
  - ps: Test-ModuleManifest -Path .\PSF.psd1 -Verbose -ErrorAction Stop
  - ps: | 
      $DestPath = "C:\Users\appveyor\Documents\WindowsPowerShell\Modules\PSF\"
      New-Item -Path $DestPath -Type Directory -Force
      Copy-Item .\PSF.ps* $DestPath

deploy_script:
  - ps: |
      if($env:APPVEYOR_PULL_REQUEST_TITLE = '' -and $env:APPVEYOR_REPO_BRANCH -eq 'master'){
        Publish-Module -Name PSF -NuGetApiKey "$env:APIKey" -Verbose 
      } else { 
        Write-Warning "Not publishing module as we are on branch '$env:APPVEYOR_REPO_BRANCH' (or we are processing a Pull Request)."
      }

artifacts:
  - path: (pwd).Path
    name: PSF Module
    type: zip
