image: WMF 5
environment:
  APIKey:
    secure: v711B0A/aGDr4wVCW3sYtaJJljC+rXipS2PENvcBC+qtOs4VXS9QWDTMJyQIKLTv

install:
  - choco install gitversion.portable -pre -y
  - rm C:\Tools\GitVersion\GitVersion.exe
  - ps: Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force

before_test:
  - ps: gitversion /l console /output buildserver
  - ps: Update-ModuleManifest -Path .\PSF.psd1 -ModuleVersion $env:GitVersion_AssemblySemVer

test_script:
  - ps: Test-ModuleManifest -Path .\PSF.psd1 -Verbose -ErrorAction Stop

deploy_script:
  - ps: if($env:APPVEYOR_REPO_TAG){ Publish-Module -Path (pwd).Path -NuGetApiKey "$env:APIKey" -Verbose } else { Publish-Module -Path (pwd).Path -NuGetApiKey "$env:APIKey" -Verbose -WhatIf }

artifacts:
  - path: .\
    name: PSF Module
    type: zip
