image: WMF 5
environment:
  APIKey:
    secure: v711B0A/aGDr4wVCW3sYtaJJljC+rXipS2PENvcBC+qtOs4VXS9QWDTMJyQIKLTv

install:
  - gitversion /version
  # - choco install gitversion.portable -y
  # - rm C:\Tools\GitVersion\GitVersion.exe
  # - gitversion /version
  - ps: Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force

before_build:
  - ps: gitversion /l console /output buildserver
  - ps: Update-ModuleManifest -Path .\PSF.psd1 -ModuleVersion $env:GitVersion_MajorMinorPatch

build_script:
  - ps: Test-ModuleManifest -Path .\PSF.psd1 -Verbose -ErrorAction Stop
  - ps: .\.ExecuteTests.ps1
  - ps: |
      $DestPath = "C:\Users\appveyor\Documents\WindowsPowerShell\Modules\PSF\"
      New-Item -Path $DestPath -Type Directory -Force
      Copy-Item .\PSF.ps* $DestPath
      Copy-Item .\functions $DestPath -Recurse

after_build:
  - 7z a -r PSF.zip %APPVEYOR_BUILD_FOLDER%\PSF.ps* %APPVEYOR_BUILD_FOLDER%\functions

deploy_script:
  - ps: |
      if($env:APPVEYOR_REPO_BRANCH -eq 'master' -and $env:APPVEYOR_REPO_TAG){
        Publish-Module -Name PSF -NuGetApiKey "$env:APIKey" -Verbose -Force
      } else {
        Write-Warning "Not publishing module as we are not on master branch, or not building a tag.`nBranch = '$env:APPVEYOR_REPO_BRANCH'`nTag = '$env:APPVEYOR_REPO_TAG'"
      }

artifacts:
  - path: PSF.zip
    name: PSF Module
